const instagramFeed = [
  {
    id: 1,
    username: "food.explorer",
    time: "1h",
    profileImg: "https://source.unsplash.com/random/?kitchen",
    postImg: "https://source.unsplash.com/random/?food",
    mutualFrndImg1: "https://source.unsplash.com/random/?boy",
    mutualFrndImg2: "https://source.unsplash.com/random/?girl",
    likeCount: "2, 00, 000",
    caption: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    commentCount: "100",
    comment: "Hello",
    backgroundImg: "https://source.unsplash.com/random/?food",
  },
  {
    id: 2,
    username: "nature.lover",
    time: "1h",
    profileImg: "https://source.unsplash.com/random/?adventure",
    postImg: "https://source.unsplash.com/random/?nature",
    mutualFrndImg1: "https://source.unsplash.com/random/?girl",
    mutualFrndImg2: "https://source.unsplash.com/random/?boy",
    likeCount: "2, 00, 000",
    caption:
      "Many touriest came nepal from all over the world to explore the beauty of the land & see the amazing natural places.",
    commentCount: "100",
    comment: "hi",
  },
  {
    id: 3,
    username: "reelsofworld",
    time: "1h",
    profileImg: "https://source.unsplash.com/random/?videography",
    postImg: "https://source.unsplash.com/random/?sport",
    mutualFrndImg1: "https://source.unsplash.com/random/?girl",
    mutualFrndImg2: "https://source.unsplash.com/random/?boy",
    likeCount: "2, 00, 000",
    caption: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    commentCount: "100",
    comment: "good",
  },
  {
    id: 4,
    username: "carlover",
    time: "1h",
    profileImg: "https://source.unsplash.com/random/?luxurycar",
    postImg: "https://source.unsplash.com/random/?car",
    mutualFrndImg1: "https://source.unsplash.com/random/?girl",
    mutualFrndImg2: "https://source.unsplash.com/random/?boy",
    likeCount: "2, 00, 000",
    caption:
      "Many touriest came nepal from all over the world to explore the beauty of the land & see the amazing natural places.",
    commentCount: "100",
  },
  {
    id: 5,
    username: "godness",
    time: "1h",
    profileImg: "https://source.unsplash.com/random/?godness",
    postImg: "https://source.unsplash.com/random/?god",
    mutualFrndImg1: "https://source.unsplash.com/random/?boy",
    mutualFrndImg2: "https://source.unsplash.com/random/?girl",
    likeCount: "2, 00, 000",
    caption: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    commentCount: "100",
  },
];

export default instagramFeed;
