const ProfileData = [
  {
    id: 1,
    name: "Priyanshu Bhatt",
    bio: "Alumni batch 2024",
    backgroundImg: "https://source.unsplash.com/random/?food",
    comment1: "loved this post",
    comment2: "loved this post",
    district: "Dehradun",
    state: "Uttarakhand",
    country: "India",
    link: "#",
    phone: "1234567890",
    email: "nobody123@xyz.com",
    profileImg: "https://source.unsplash.com/random/?kitchen",
    utu: "/utu.png",
    sampleImg1: "/sample.png",
    sampleImg2: "/sample2.png",
    sampleEImg: "/institute.avif",
    skill: "FrontEnd Developer",
    education: "Uttarakhand Technical University",
    degree: "Bachelor of Technology",
    achivement: "Winner in Hackathon",
    para: "Won the hackathon of 2k23",
    notification: "event #1 for the alumni's",
    Role: "Internship",
    CompanyName: "THDC India Limited Official",
    Experience: "Intern",
    Endedin: "Aug 2024",
    started: "Oct 2021",
    degreein: "Computer Science",
    achivDateStart: "15 May 2023",
    achivDateEnd: "23 May 2023",
    notification: "event #1 for the alumni's",
    caption: "first post",
  },
  {
    id: 2,
    name: "Priyanshu Bhatt",
    bio: "Alumni batch 2024",
    comment1: "loved this post",
    comment2: "loved this post",
    profileImg: "https://source.unsplash.com/random/?kitchen",
    utu: "/utu.png",
    sampleImg1: "/sample.png",
    sampleImg2: "/sample2.png",
    sampleEImg: "/institute.avif",
    skill: "Backend Developer",
    education: "Government Polytechnic Shyampur",
    notification: "event #2 for the alumni's",
    achivDateStart: "14 Sept 2024",
    achivement: "Participated in TechSummit",
    achivDateEnd: "14 Sept 2024",
    para: "Participated in the Techsummit held in the college 2k24",
    CompanyName: "Google",
    Role: "Full Time",
    started: "Aug 2018",
    Endedin: "Oct 2021",
    Experience: "Full Stack Developer",
    degree: "Diploma of Education",
    degreein: "Electrical Engineering",
    notification: "event #2 for the alumni's",
    district: "Dehradun",
    state: "Uttarakhand",
    country: "India",
    caption: "first post",
  },
  {
    id: 3,
    comment1: "loved this post",
    comment2: "loved this post",
    profileImg: "https://source.unsplash.com/random/?kitchen",
    utu: "/utu.png",
    sampleImg1: "/sample.png",
    sampleImg2: "/sample2.png",
    sampleEImg: "/institute.avif",
    skill: "Backend Developer",
    education: "Government Polytechnic Shyampur",
    notification: "event #2 for the alumni's",
    achivDateStart: "14 Sept 2024",
    achivement: "Participated in TechSummit",
    achivDateEnd: "14 Sept 2024",
    para: "Participated in the Techsummit held in the college 2k24",
    CompanyName: "Google",
    Role: "Full Time",
    started: "Aug 2018",
    Endedin: "Oct 2021",
    Experience: "Full Stack Developer",
    degree: "Diploma of Education",
    degreein: "Electrical Engineering",
    notification: "event #3 for the alumni's",
    district: "Dehradun",
    state: "Uttarakhand",
    country: "India",
    caption: "first post",
  },
];

export default ProfileData;
